baseURL = "https://lovesong99.github.io/"

languageCode = "zh-TW"
DefaultContentLanguage = "zh"
title = "戀戀「山」歌－李茂山非官方歌迷網站"
theme = "docdock"
googleAnalytics = "UA-40443654-5"
# themesdir = "../.."
pygmentsCodeFences = true
pygmentsStyle = "monokailight"
footnoteReturnLinkContents = "↩"
hasCJKLanguage = true
summaryLength = 150

defaultContentLanguage = "zh"
defaultContentLanguageInSubdir= false
enableMissingTranslationPlaceholders = false


# [Languages]
# [Languages.en]
# title = "Documentation for Hugo docDock"
# weight = 1
# languageName = "English"
# 
# [Languages.fr]
# title = "Documentation du thème docDock"
# weight = 2
# languageName = "Français"




[params]
# editURL = "https://github.com/vjeantet/hugo-theme-docdock/edit/master/exampleSite/content/"
showVisitedLinks = true # default is false
themeStyle = "flex" # "original" or "flex" # default "flex"
themeVariant = "" # choose theme variant "green", "gold" , "gray", "blue" (default)
ordersectionsby = "weight" # ordersectionsby = "title"
disableHomeIcon = false # default is false
disableSearch = false # default is false
disableNavChevron = false # set true to hide next/prev chevron, default is false
highlightClientSide = false # set true to use highlight.pack.js instead of the default hugo chroma highlighter
menushortcutsnewtab = true # set true to open shortcuts links to a new tab/window
enableGitInfo = false

[outputs]
home = [ "HTML", "RSS", "JSON"]


 [[menu.shortcuts]]
name = "<i class='fa fa-shopping-cart'></i> <label>瑞華唱片官方Lazada商城（星馬地區）</label>"
url = "https://www.lazada.com.my/shop/suwah-music/"
weight = 10

[[menu.shortcuts]]
name = "<i class='fa fa-facebook-official'></i> <label>瑞華唱片Facebook</label>"
url = "https://www.facebook.com/SuwahMusic/"
weight = 20

[[menu.shortcuts]]
name = "<i class='fa fa-bullhorn'></i> <label>光美唱片官方網站</label>"
url = "http://www.kuangmei.com.tw/"
weight = 30

# [[menu.shortcuts]]
# name = "<i class='fa fa-bookmark'></i> <label>Hugo Documentation</label>"
# identifier = "hugodoc"
# url = "https://gohugo.io/"
# weight = 20

